name: Build SuperRyzen Kernel

on:
  push:
    branches: caf

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build SuperRyzen Kernel
        run: |
          wget https://raw.githubusercontent.com/cari-404/SRyzen-CAF/caf/build-start.sh
          bash build-start.sh stable clang
          cd kernel
          mkdir kernel-done
          wget https://raw.githubusercontent.com/cari-404/SRyzen-CAF/caf/build-dtb.sh
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          bash build-dtb.sh tulip clang qpnp
          git apply qti.patch
          bash build-dtb.sh tulip clang qti
          git restore .
          wget https://raw.githubusercontent.com/cari-404/SRyzen-CAF/caf/build.sh
          bash build.sh tulip newcam clang
          bash build.sh tulip oldcam clang
          git apply oc.patch
          bash build-dtb.sh tulip clang qpnp
          git apply qti.patch
          bash build-dtb.sh tulip clang qti
          git restore .
          bash build.sh tulip newcam oc clang
          bash build.sh tulip oldcam oc clang
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tulip
          path: kernel/ak3-tulip/*
                
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: kernel/kernel-done/*
          
